#ifndef CSCI437_CONSTANTS_H
#define CSCI437_CONSTANTS_H

//enum mapping actor types to ints
enum ACTOR_IDS {PLAYER, PLATFORM, WALKING_ENEMY, LOBBING_ENEMY, FLYING_ENEMY, LEG, TYRANTULA,
PLAYER_PISTOL_PROJECTILE,PLAYER_SPREAD_PROJECTILE,ENEMY_PISTOL_PROJECTILE, ENEMY_LOBBING_PROJECTILE ,SPIKE, LEVEL_PICKUP, HEALTH_PICKUP, LEVEL_END};
enum states {UNINITIALIZED, RUNNING, PAUSED, DESTROYED, TEMP};

#endif //CSCI437_CONSTANTS_H